#!/bin/sh

yes=yes

echo "Active users:"
users
echo -e "\nType the user you want to delete:"
read user
echo "Are you sure you want to remove the user '$user' and all its files?[yes/no]"
read answer
if [ "$answer" == "$yes" ]  && [ "$user" != "root" ]
then
	sudo pkill -u $user
	sudo userdel -r $user
	echo "User deleted succesfully"
	exit 0
else
	echo "No user has been deleted"
	exit 0
fi
